# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{twitter-fusefs}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["chmeee"]
  s.date = %q{2009-08-20}
  s.default_executable = %q{twitter-fusefs}
  s.description = %q{Mount your twitter account as a userspace filesystem, access your tweets as files, update echo'ing over files}
  s.email = %q{chmeee@gmail.com}
  s.executables = ["twitter-fusefs"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/twitter-fusefs",
     "helpers/config_store.rb",
     "lib/twitter-fusefs.rb",
     "lib/twitter_account.rb",
     "test/test_helper.rb",
     "test/twitter-fusefs_test.rb"
  ]
  s.homepage = %q{http://github.com/chmeee/twitter-fusefs}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Access twitter as a filesystem}
  s.test_files = [
    "test/test_helper.rb",
     "test/twitter-fusefs_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<twitter>, [">= 0"])
    else
      s.add_dependency(%q<twitter>, [">= 0"])
    end
  else
    s.add_dependency(%q<twitter>, [">= 0"])
  end
end
